/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    projects: Project;
    initiatives: Initiative;
    teams: Team;
    members: Member;
    statuses: Status;
    cycles: Cycle;
    'label-groups': LabelGroup;
    labels: Label;
    tickets: Ticket;
    comments: Comment;
    attachments: Attachment;
    activity: Activity;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    initiatives: InitiativesSelect<false> | InitiativesSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    statuses: StatusesSelect<false> | StatusesSelect<true>;
    cycles: CyclesSelect<false> | CyclesSelect<true>;
    'label-groups': LabelGroupsSelect<false> | LabelGroupsSelect<true>;
    labels: LabelsSelect<false> | LabelsSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    attachments: AttachmentsSelect<false> | AttachmentsSelect<true>;
    activity: ActivitySelect<false> | ActivitySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      cycleRollover: TaskCycleRollover;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Login accounts and API keys. These are credentials, not assignable people — tickets are assigned to a team.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Display name for this account
   */
  name?: string | null;
  /**
   * admin may delete records and manage accounts; member may read and write; agent is an automated caller and should hold an API key rather than a password. Defaults to admin so the first account created can administer the install.
   */
  role: 'admin' | 'member' | 'agent';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Projects organize related tickets together
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  /**
   * The name of the project
   */
  name: string;
  /**
   * Short prefix for ticket IDs (e.g., PROJ for PROJ-123)
   */
  prefix: string;
  /**
   * Detailed description of the project
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Icon to represent the project
   */
  icon?:
    | (
        | 'folder'
        | 'rocket'
        | 'zap'
        | 'star'
        | 'heart'
        | 'flag'
        | 'target'
        | 'briefcase'
        | 'code'
        | 'box'
        | 'layers'
        | 'database'
        | 'megaphone'
        | 'cloud'
        | 'users'
      )
    | null;
  /**
   * Color theme for the project
   */
  color?:
    | (
        | '#6366f1'
        | '#8b5cf6'
        | '#a855f7'
        | '#d946ef'
        | '#ec4899'
        | '#ef4444'
        | '#f97316'
        | '#f59e0b'
        | '#eab308'
        | '#22c55e'
        | '#14b8a6'
        | '#06b6d4'
        | '#3b82f6'
      )
    | null;
  /**
   * Current status of the project
   */
  status: 'ACTIVE' | 'ON_HOLD' | 'COMPLETED' | 'CANCELLED';
  /**
   * When work on this project is meant to begin
   */
  startDate?: string | null;
  /**
   * The date this project is aiming to finish by
   */
  targetDate?: string | null;
  /**
   * Time-boxed cycles for this project
   */
  cycles?: {
    /**
     * Turn cycles on for this project. Off by default.
     */
    enabled?: boolean | null;
    /**
     * How long each cycle runs. Applies to cycles created from now on.
     */
    lengthWeeks?: number | null;
    /**
     * Weekday the first cycle starts on, 0 being Sunday
     */
    startDay?: number | null;
    /**
     * Where incomplete tickets go when a cycle closes
     */
    rollover?: ('NEXT' | 'BACKLOG' | 'NONE') | null;
    /**
     * Automatic closes elapsed cycles on the server on a schedule. Manual waits for someone to close each cycle.
     */
    automation?: ('AUTOMATIC' | 'MANUAL') | null;
    /**
     * How many future cycles to keep provisioned ahead of the active one
     */
    upcomingCount?: number | null;
  };
  /**
   * A holding queue for incoming work, reviewed before it reaches the backlog
   */
  triage?: {
    /**
     * Turn triage on for this project. Off by default. Enabling it adds a Triage status that the board and list views leave out.
     */
    enabled?: boolean | null;
  };
  /**
   * Effort estimates for tickets in this project
   */
  estimates?: {
    /**
     * Turn estimates on for this project. Off by default, and cycle charts count tickets instead.
     */
    enabled?: boolean | null;
    /**
     * How estimates are written. Changing it relabels existing estimates without rewriting them.
     */
    scale?: ('LINEAR' | 'FIBONACCI' | 'EXPONENTIAL' | 'TSHIRT') | null;
  };
  /**
   * Auto-incremented counter for ticket IDs
   */
  ticketCounter?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A layer above projects that rolls several of them up into one objective
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "initiatives".
 */
export interface Initiative {
  id: string;
  /**
   * What this initiative is trying to achieve
   */
  name: string;
  /**
   * The objective, its scope, and how success is judged
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Where this initiative sits in its life
   */
  status: 'PLANNED' | 'ACTIVE' | 'COMPLETED' | 'CANCELLED';
  /**
   * The projects this initiative rolls up. A project can belong to several initiatives.
   */
  projects?: (string | Project)[] | null;
  /**
   * The person accountable for this initiative
   */
  lead?: (string | null) | Member;
  /**
   * The date this initiative is aiming at
   */
  targetDate?: string | null;
  /**
   * Icon to represent the initiative
   */
  icon?:
    | ('target' | 'rocket' | 'flag' | 'star' | 'zap' | 'layers' | 'briefcase' | 'megaphone' | 'heart' | 'cloud')
    | null;
  /**
   * Colour theme for the initiative
   */
  color?:
    | (
        | '#6366f1'
        | '#8b5cf6'
        | '#a855f7'
        | '#d946ef'
        | '#ec4899'
        | '#ef4444'
        | '#f97316'
        | '#f59e0b'
        | '#eab308'
        | '#22c55e'
        | '#14b8a6'
        | '#06b6d4'
        | '#3b82f6'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People that tickets can be assigned to.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: string;
  /**
   * Display name — what shows on cards and in pickers
   */
  name: string;
  /**
   * Optional. Used to tell two people with the same name apart.
   */
  email?: string | null;
  /**
   * The team this person belongs to
   */
  team?: (string | null) | Team;
  /**
   * Inactive people keep their existing assignments but drop out of the assignee pickers.
   */
  active?: boolean | null;
  /**
   * The login account this person signs in with. Set it and "My tickets" works for them.
   */
  user?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Teams group related work within a project
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: string;
  /**
   * The name of the team
   */
  name: string;
  /**
   * Brief description of the team
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Color for team identification
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Workflow states a ticket can occupy, globally or per project
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statuses".
 */
export interface Status {
  id: string;
  /**
   * The label shown on the board column and on tickets
   */
  name: string;
  /**
   * Stable identifier used by the API and the MCP server. Derived from the name.
   */
  key: string;
  /**
   * The semantic category. Drives the icon, the tone, and whether a ticket counts as open or closed.
   */
  type: 'TRIAGE' | 'BACKLOG' | 'UNSTARTED' | 'STARTED' | 'COMPLETED' | 'CANCELLED';
  /**
   * Column position, ascending. Gaps are intentional so a status can be inserted.
   */
  order: number;
  /**
   * Leave empty for a workspace-wide status. Set it to scope the status to one project.
   */
  project?: (string | null) | Project;
  /**
   * Optional hint shown when picking this status
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Time-boxed cycles that incomplete work rolls out of when they end
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cycles".
 */
export interface Cycle {
  id: string;
  /**
   * Shown on the cycle page and on tickets. Defaults to the cycle number.
   */
  name: string;
  /**
   * Sequential within the project, starting at 1. Never reused.
   */
  number: number;
  /**
   * The project whose workflow this cycle belongs to
   */
  project: string | Project;
  /**
   * First day of the cycle
   */
  startsAt: string;
  /**
   * Last day of the cycle, inclusive
   */
  endsAt: string;
  /**
   * Optional one-line goal for the cycle
   */
  goal?: string | null;
  /**
   * Set when the cycle was closed and its incomplete work rolled over
   */
  completedAt?: string | null;
  /**
   * The burndown as it stood when the cycle closed. Frozen so the chart keeps reading the same afterwards, whatever happens to the tickets later.
   */
  progressSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * How many tickets moved out of this cycle when it closed
   */
  rolledOver?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Optional clusters that labels can belong to, such as Area or Kind
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "label-groups".
 */
export interface LabelGroup {
  id: string;
  /**
   * The heading this group gets in the label picker
   */
  name: string;
  /**
   * Stable identifier used by the API and the MCP server. Derived from the name.
   */
  key: string;
  /**
   * Position in the picker, ascending. Gaps are intentional.
   */
  order: number;
  /**
   * Optional hint shown beside the group heading
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Shared labels that any ticket in the workspace can carry
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labels".
 */
export interface Label {
  id: string;
  /**
   * What the label reads as on a card. One or two words.
   */
  name: string;
  /**
   * Stable identifier used by the API and the MCP server. Derived from the name.
   */
  key: string;
  /**
   * The swatch shown beside the name. The palette is fixed so colour stays mappable to meaning.
   */
  color: 'SLATE' | 'INDIGO' | 'BLUE' | 'GREEN' | 'AMBER' | 'RED';
  /**
   * Optional. Groups cluster related labels in the picker.
   */
  group?: (string | null) | LabelGroup;
  /**
   * Optional hint shown when picking this label
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual work items within projects
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: string;
  /**
   * Auto-generated ticket ID (e.g., PROJ-123)
   */
  ticketId?: string | null;
  /**
   * Brief title of the ticket
   */
  title: string;
  /**
   * Detailed description of the work
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Current status of the ticket, drawn from its project workflow
   */
  status: string | Status;
  /**
   * Priority level of the ticket
   */
  priority?: ('NO_PRIORITY' | 'URGENT' | 'HIGH' | 'MEDIUM' | 'LOW') | null;
  /**
   * The project this ticket belongs to
   */
  project: string | Project;
  /**
   * The team responsible for this ticket
   */
  team?: (string | null) | Team;
  /**
   * The cycle this ticket is committed to, when the project runs cycles
   */
  cycle?: (string | null) | Cycle;
  /**
   * The person responsible for this ticket
   */
  assignee?: (string | null) | Member;
  /**
   * Tickets that must be completed before this ticket can be worked on
   */
  blockedBy?: (string | Ticket)[] | null;
  /**
   * Shared labels drawn from the workspace label set
   */
  labels?: (string | Label)[] | null;
  /**
   * How much work this is, in points. The project picks the scale it is shown in; t-shirt sizes are stored as their point value so they still add up.
   */
  estimate?: number | null;
  /**
   * When work on this ticket is meant to begin
   */
  startDate?: string | null;
  /**
   * When this ticket should be completed
   */
  dueDate?: string | null;
  /**
   * The canonical ticket this one duplicates. Set when a triage item is merged into existing work.
   */
  duplicateOf?: (string | null) | Ticket;
  /**
   * Hide this from the triage queue until this date, or until someone touches it
   */
  snoozedUntil?: string | null;
  /**
   * Mark this ticket as an epic so other tickets in the same project can roll up into it
   */
  isEpic?: boolean | null;
  /**
   * The epic this ticket rolls up into. An epic and its children share a project, and epics do not nest.
   */
  epic?: (string | null) | Ticket;
  /**
   * Subtasks for this ticket
   */
  subtasks?:
    | {
        title: string;
        completed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Order within the column
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Discussion on tickets. A reply points at the comment that opened the thread.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: string;
  /**
   * The ticket this comment belongs to
   */
  ticket: string | Ticket;
  /**
   * The comment that opened this thread. Empty for a top-level comment. Threads are one level deep.
   */
  parent?: (string | null) | Comment;
  /**
   * Markdown. Mentions are stored as @[Name](member:ID) and render as a chip.
   */
  body: string;
  /**
   * Who wrote this. Filled from the signed-in account when the caller does not set it.
   */
  author?: (string | null) | Member;
  /**
   * Derived from the body on every save. Do not edit by hand.
   */
  mentions?: (string | Member)[] | null;
  /**
   * A resolved thread collapses. Only the first comment in a thread carries it.
   */
  resolved?: boolean | null;
  resolvedAt?: string | null;
  resolvedBy?: (string | null) | Member;
  editedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Files dropped, pasted, or picked inside a comment or a description.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attachments".
 */
export interface Attachment {
  id: string;
  /**
   * What the image shows, for anyone who cannot see it.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Append-only record of what changed on a ticket, and who changed it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity".
 */
export interface Activity {
  id: string;
  /**
   * The ticket this entry belongs to
   */
  ticket: string | Ticket;
  action: 'created' | 'changed' | 'commented' | 'replied' | 'edited' | 'resolved' | 'reopened' | 'deleted';
  /**
   * The comment this entry is about. Empty once that comment is deleted.
   */
  comment?: (string | null) | Comment;
  /**
   * Which field changed. Empty when the ticket was created.
   */
  field?: string | null;
  /**
   * The value, or comment text, as it read before the change
   */
  from?: string | null;
  /**
   * The value, or comment text, as it read after the change
   */
  to?: string | null;
  /**
   * The id behind `from`, when the value was a record. Lets reports replay history exactly instead of matching on a name that may since have changed.
   */
  fromId?: string | null;
  /**
   * The id behind `to`, when the value was a record
   */
  toId?: string | null;
  /**
   * Who made the change. Empty when nobody was signed in.
   */
  actor?: (string | null) | Member;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'cycleRollover';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'cycleRollover') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'initiatives';
        value: string | Initiative;
      } | null)
    | ({
        relationTo: 'teams';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'members';
        value: string | Member;
      } | null)
    | ({
        relationTo: 'statuses';
        value: string | Status;
      } | null)
    | ({
        relationTo: 'cycles';
        value: string | Cycle;
      } | null)
    | ({
        relationTo: 'label-groups';
        value: string | LabelGroup;
      } | null)
    | ({
        relationTo: 'labels';
        value: string | Label;
      } | null)
    | ({
        relationTo: 'tickets';
        value: string | Ticket;
      } | null)
    | ({
        relationTo: 'comments';
        value: string | Comment;
      } | null)
    | ({
        relationTo: 'attachments';
        value: string | Attachment;
      } | null)
    | ({
        relationTo: 'activity';
        value: string | Activity;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  prefix?: T;
  description?: T;
  icon?: T;
  color?: T;
  status?: T;
  startDate?: T;
  targetDate?: T;
  cycles?:
    | T
    | {
        enabled?: T;
        lengthWeeks?: T;
        startDay?: T;
        rollover?: T;
        automation?: T;
        upcomingCount?: T;
      };
  triage?:
    | T
    | {
        enabled?: T;
      };
  estimates?:
    | T
    | {
        enabled?: T;
        scale?: T;
      };
  ticketCounter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "initiatives_select".
 */
export interface InitiativesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  status?: T;
  projects?: T;
  lead?: T;
  targetDate?: T;
  icon?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  team?: T;
  active?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statuses_select".
 */
export interface StatusesSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  type?: T;
  order?: T;
  project?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cycles_select".
 */
export interface CyclesSelect<T extends boolean = true> {
  name?: T;
  number?: T;
  project?: T;
  startsAt?: T;
  endsAt?: T;
  goal?: T;
  completedAt?: T;
  progressSnapshot?: T;
  rolledOver?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "label-groups_select".
 */
export interface LabelGroupsSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  order?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labels_select".
 */
export interface LabelsSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  color?: T;
  group?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  ticketId?: T;
  title?: T;
  description?: T;
  status?: T;
  priority?: T;
  project?: T;
  team?: T;
  cycle?: T;
  assignee?: T;
  blockedBy?: T;
  labels?: T;
  estimate?: T;
  startDate?: T;
  dueDate?: T;
  duplicateOf?: T;
  snoozedUntil?: T;
  isEpic?: T;
  epic?: T;
  subtasks?:
    | T
    | {
        title?: T;
        completed?: T;
        id?: T;
      };
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  ticket?: T;
  parent?: T;
  body?: T;
  author?: T;
  mentions?: T;
  resolved?: T;
  resolvedAt?: T;
  resolvedBy?: T;
  editedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attachments_select".
 */
export interface AttachmentsSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_select".
 */
export interface ActivitySelect<T extends boolean = true> {
  ticket?: T;
  action?: T;
  comment?: T;
  field?: T;
  from?: T;
  to?: T;
  fromId?: T;
  toId?: T;
  actor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCycleRollover".
 */
export interface TaskCycleRollover {
  input?: unknown;
  output: {
    projects?: number | null;
    created?: number | null;
    closed?: number | null;
    rolledOver?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}